package com.gameloft9.demo.dataaccess.dao.system;

import com.gameloft9.demo.dataaccess.model.system.SysOrganizeTest;
import com.gameloft9.demo.dataaccess.model.tp.TpDepartment;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TpDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORGANIZE_TEST
     *
     * @mbggenerated Thu Dec 07 15:21:02 CST 2017
     */
    int deleteByPrimaryKey(int departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORGANIZE_TEST
     *
     * @mbggenerated Thu Dec 07 15:21:02 CST 2017
     */
    int insert(TpDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORGANIZE_TEST
     *
     * @mbggenerated Thu Dec 07 15:21:02 CST 2017
     */
    int insertSelective(TpDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORGANIZE_TEST
     *
     * @mbggenerated Thu Dec 07 15:21:02 CST 2017
     */
    TpDepartment selectByPrimaryKey(int departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORGANIZE_TEST
     *
     * @mbggenerated Thu Dec 07 15:21:02 CST 2017
     */
    int updateByPrimaryKeySelective(TpDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ORGANIZE_TEST
     *
     * @mbggenerated Thu Dec 07 15:21:02 CST 2017
     */
    int updateByPrimaryKey(TpDepartment record);


    /**
     * 获取所有组织机构
     * */
    List<TpDepartment> getAll();

    /**
     * 获取子机构个数
     * @param superiorDepartment 父机构id
     * */
    int countChildren(@Param("superiorDepartment") String superiorDepartment);

    /**
     * 根据名称获取组织机构
     * @param departmentName 组织机构名称
     * */
    TpDepartment getByName(@Param("departmentName") String departmentName);

    /**
     * 获取根组织机构
     * */
    TpDepartment getRoot();

    /**
     * 找到某一层机构最大序号
     * @param level 机构层级
     * */
    String getMaxOrgCode(@Param("level") int level);
}